// sidebars.js

/**
 * Creating a sidebar enables you to create a multiple sidebar configuration for your
 * site with a single docs folder.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Define la barra lateral principal usando el ID 'lspdSidebar'
  lspdSidebar: [
    'intro', // 'intro.md' (Archivo inicial)

    // CATEGORÍAS AUTOGENERADAS DESDE LAS CARPETAS
    {
        type: 'autogenerated',
        dirName: 'nosotros', 
    },
    {
        type: 'autogenerated',
        dirName: 'rangos', 
    },
    {
        type: 'autogenerated',
        dirName: 'normativa', 
    },
    {
        type: 'autogenerated',
        dirName: 'reclutamiento', 
    },
    // NOTA: Si eliminaste las carpetas de ejemplo, el resto del contenido
    // de este archivo debe estar limpio, como se muestra aquí.
  ],
};

module.exports = sidebars;