// sidebars.js

/**
 * Creating a sidebar enables you to create a multiple sidebar configuration for your
 * site with a single docs folder.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Define la barra lateral principal de la documentación
  lspdSidebar: [
    'intro', // 'intro.md' (Archivo inicial)

    // CATEGORÍAS AUTOGENERADAS DESDE LAS CARPETAS
    {
        type: 'autogenerated',
        dirName: 'nosotros', 
    },
    {
        type: 'autogenerated',
        dirName: 'rangos', 
    },
    {
        type: 'autogenerated',
        dirName: 'normativa', 
    },
    {
        type: 'autogenerated',
        dirName: 'reclutamiento', 
    },
  ],
};

module.exports = sidebars;